name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: aiplan4eu/unified-planning

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Checkout the Unified Planning Framework
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/unified-planning
          path: unified-planning

      - name: Install Unified-Planning
        run: python3 -m pip install unified-planning/

      - name: Checkout Pyperplan Unified-Planning interface
        uses: actions/checkout@v2
        with:
          repository: aiplan4eu/up-pyperplan
          path: up-pyperplan

      - name: Install Pyperplan Unified-Planning interface
        run: python3 -m pip install up-pyperplan/

      - name: Run tests
        run: python3 runner.py